#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────
# dsh-astra install script (GitHub direct)
# Installs the starfield plugin into dsh-TUI profile.
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/lql341/dsh-astra/main/install.sh | bash
#   # or
#   git clone https://github.com/lql341/dsh-astra && cd dsh-astra && bash install.sh
# ──────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { printf "${CYAN}→${NC} %s\n" "$*"; }
ok()    { printf "${GREEN}✓${NC} %s\n" "$*"; }
err()   { printf "${RED}✗${NC} %s\n" "$*" >&2; }

# ── Prerequisites ────────────────────────────
command -v dsh >/dev/null 2>&1 || { err "dsh CLI not found. Install: npm i -g @deepseek-ai/dsh"; exit 1; }
command -v node >/dev/null 2>&1 || { err "Node.js not found."; exit 1; }

info "dsh-astra installer (GitHub direct)"

# ── Detect profile ───────────────────────────
PROFILE="${DSH_TUI_PROFILE:-dsh-tui}"
DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
PROFILE_DIR="$DSH_HOME/profiles/$PROFILE"

if [ -d "$PROFILE_DIR" ]; then
  ok "dsh-TUI profile '$PROFILE' found at $PROFILE_DIR"
else
  info "Profile '$PROFILE' not found. Creating a minimal dsh-TUI profile first..."
  dsh plugin --profile "$PROFILE" add @deepseek-harness-tui/dsh-tui 2>/dev/null || {
    # If the plugin add fails, try manual approach
    mkdir -p "$PROFILE_DIR"
    cat > "$PROFILE_DIR/cordis.yml" << 'CORDIS'
# dsh-TUI profile (generated by dsh-astra installer)
services:
  - id: dsh-tui
    name: '@deepseek-harness-tui/dsh-tui'
    config:
      fullscreen: true
CORDIS
    ok "Created minimal profile at $PROFILE_DIR/cordis.yml"
  }
fi

# ── Determine plugin source ──────────────────
# If we're inside the repo directory, use the local copy.
# Otherwise clone from GitHub.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_JSON="$SCRIPT_DIR/package.json"

if [ -f "$PKG_JSON" ] && grep -q '"dsh-astra"' "$PKG_JSON" 2>/dev/null; then
  info "Using local repo: $SCRIPT_DIR"
  PLUGIN_SRC="$SCRIPT_DIR"
else
  REPO_URL="https://github.com/lql341/dsh-astra.git"
  TMP_DIR="$(mktemp -d)"
  info "Cloning $REPO_URL ..."
  git clone --depth 1 "$REPO_URL" "$TMP_DIR" 2>/dev/null || {
    err "Failed to clone $REPO_URL"
    exit 1
  }
  PLUGIN_SRC="$TMP_DIR"
fi

# ── Build the plugin ─────────────────────────
info "Building dsh-astra ..."
cd "$PLUGIN_SRC"

if [ -f "pnpm-lock.yaml" ]; then
  pnpm install --frozen-lockfile 2>/dev/null || pnpm install
else
  npm install --no-audit --no-fund 2>/dev/null || true
fi

# Compile TypeScript → lib/
npx tsc -p tsconfig.json 2>/dev/null || {
  err "TypeScript build failed; refusing to install an incomplete plugin"
  err "Install dependencies with pnpm/npm, then run: pnpm build"
  exit 1
}

ok "Build complete"

# ── Install into profile ─────────────────────
info "Adding dsh-astra to profile '$PROFILE' ..."

# Patch the cordis.yml to include dsh-astra row
PATCH_FILE="$PLUGIN_SRC/cordis.patch.yml"
if [ -f "$PATCH_FILE" ]; then
  # Try the dsh CLI way first
  dsh plugin --profile "$PROFILE" add "$PLUGIN_SRC" 2>/dev/null && {
    ok "Installed via dsh plugin add"
  } || {
    # Fallback: manually insert into cordis.yml
    info "Manual profile patch ..."
    CORDIS_YML="$PROFILE_DIR/cordis.yml"

    if grep -q 'dsh-astra' "$CORDIS_YML" 2>/dev/null; then
      ok "dsh-astra already in cordis.yml, skipping"
    else
      # Append the plugin as a service row
      cat >> "$CORDIS_YML" << 'ROW'

  - id: dsh-astra
    name: 'dsh-astra'
    config:
      enabled: true
      fps: 10
      density: sparse
ROW
      ok "Added dsh-astra row to $CORDIS_YML"
    fi
  }
fi

# ── Verification ─────────────────────────────
info "Verifying ..."

# Check the profile directory structure
PLUGIN_NODE_MODULES="$PROFILE_DIR/node_modules/dsh-astra"
if [ -d "$PLUGIN_NODE_MODULES" ]; then
  ok "Plugin linked at $PLUGIN_NODE_MODULES"
else
  info "Plugin module not in profile node_modules yet; will resolve on first launch"
fi

# ── Done ─────────────────────────────────────
echo ""
echo "  ┌─────────────────────────────────────────────┐"
echo "  │  ✨ dsh-astra installed!                     │"
echo "  │                                             │"
echo "  │  Launch:  dsh --profile $PROFILE         │"
echo "  │  Or:      dst                            │"
echo "  │                                             │"
echo "  │  Controls:                                  │"
echo "  │    /astra on      Enable starfield          │"
echo "  │    /astra off     Disable starfield         │"
echo "  │    /astra status  Show config               │"
echo "  │    /astra toggle  Toggle starfield          │"
echo "  │                                             │"
echo "  │  Env:   DSH_TUI_ASTRA_EFFECT=auto|on|off    │"
echo "  │  Repo:  https://github.com/lql341/dsh-astra │"
echo "  └─────────────────────────────────────────────┘"
echo ""
